---
repos:

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint", "-s"]

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        files: ^ansible/

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.44.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: sort-simple-yaml
      - id: trailing-whitespace
        exclude: \.txt$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: ^(lib|conf/servers)/.*$
      - id: git-check     # Configure in .gitattributes
      - id: markdownlint  # Configure in .mdlrc
      - id: reek
      # - id: require-ascii
      - id: script-must-have-extension
      # - id: shellcheck
      - id: shfmt

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
