---
- name: Setup SageMath
  hosts: localhost
  vars_files:
    - ../variables.yml
  vars:
    sage: true
  tasks:
    - name: Import Sage installation tasks
      ansible.builtin.import_tasks: tasks/sage.yml
      tags: [sage, install]
