---
- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present

- name: Download Brave browser keyring
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'

- name: Download Brave browser sources list
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    dest: /etc/apt/sources.list.d/brave-browser-release.sources
    mode: '0644'

- name: Install Brave browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
    update_cache: true
