---
- name: Install APT packages from files/apt-install-base.txt
  ansible.builtin.apt:
    name: >-
      {{
        lookup('ansible.builtin.file', '../files/apt-install-base.txt')
        .splitlines()
        | map('trim')
        | reject('equalto', '')
        | reject('match', '^#')
        | list
      }}
    state: present
    update_cache: true
