---
- name: Ensure OS is Ubuntu for MEGA
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Ubuntu'
    fail_msg: MEGA installation is currently only supported on Ubuntu.

- name: Determine architecture for MEGA
  ansible.builtin.set_fact:
    mega_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

- name: Set MEGA download URL
  ansible.builtin.set_fact:
    mega_deb_url: >-
      {{ 'https://mega.nz/linux/repo/xUbuntu_' ~ ansible_distribution_version ~
      '/' ~ mega_arch ~ '/megasync-xUbuntu_' ~ ansible_distribution_version ~
      '_' ~ mega_arch ~ '.deb' }}

- name: Download MEGA desktop app package
  ansible.builtin.get_url:
    url: "{{ mega_deb_url }}"
    dest: /tmp/megasync.deb
    mode: '0644'

- name: Install MEGA desktop app package
  ansible.builtin.apt:
    deb: /tmp/megasync.deb
    state: present
