---
- name: Install snap packages
  community.general.snap:
    name: '{{ item.name | default(item) }}'
    classic: '{{ item.classic | default(omit) }}'
    state: present
  loop: '{{ snap.install }}'
  when: snap.install is defined
