---
name: Check
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 1  # Run every Monday at 00:00 UTC
  workflow_dispatch:
jobs:
  check:
    uses: kenorb/.github/.github/workflows/check.yml@main
    with:
      submodules: 'false'  # Set to 'true' or 'recursive' if repository uses submodules
