---
# Note: Keep keys and envs in alphabetical order.
name: Development Containers (CI)
# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer-ci.yml
  push:
    branches:
      - dev
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer-ci.yml
  schedule:
    - cron: 0 0 * * 1  # Run every Monday at 00:00 UTC
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  devcontainer-build:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    # See: https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows
    uses: kenorb/.github/.github/workflows/devcontainer-ci.yml@main
    secrets: inherit  # pragma: allowlist secret
